//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroProcessor.Utils {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacroProcessor.Utils.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метка {0} при директиве {1} находится вне зоны видимости или не описана.
        /// </summary>
        internal static string AifLabelNotFound {
            get {
                return ResourceManager.GetString("AifLabelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использование директивы макрогенерации ({0}) допустимо только в макросе.
        /// </summary>
        internal static string ConditionalMacrogenerationDirectiveNotInMacro {
            get {
                return ResourceManager.GetString("ConditionalMacrogenerationDirectiveNotInMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директива {0} не содержит метку.
        /// </summary>
        internal static string DirectiveWithoutLabel {
            get {
                return ResourceManager.GetString("DirectiveWithoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дубликат метки {0} в макросе {1}.
        /// </summary>
        internal static string DublicateLabelInMacro {
            get {
                return ResourceManager.GetString("DublicateLabelInMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр {0} макроса повторяется.
        /// </summary>
        internal static string DublicateMacroCallParameter {
            get {
                return ResourceManager.GetString("DublicateMacroCallParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходный код не содержит ни одной строки.
        /// </summary>
        internal static string EmptySourceCode {
            get {
                return ResourceManager.GetString("EmptySourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переменная {0} не инициализирована.
        /// </summary>
        internal static string EmptyVariable {
            get {
                return ResourceManager.GetString("EmptyVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдена ошибка в строке &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string ErrorOccuredInLine {
            get {
                return ResourceManager.GetString("ErrorOccuredInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа обновлена.
        /// </summary>
        internal static string EverythingRefreshed {
            get {
                return ResourceManager.GetString("EverythingRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лишняя директива MEND.
        /// </summary>
        internal static string ExtraMend {
            get {
                return ResourceManager.GetString("ExtraMend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первый проход завершен.
        /// </summary>
        internal static string FirstRunFinished {
            get {
                return ResourceManager.GetString("FirstRunFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первый проход еще не завершен.
        /// </summary>
        internal static string FirstRunNotFinishedYet {
            get {
                return ResourceManager.GetString("FirstRunNotFinishedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры макровызова заданы некорректно ({0}). Разделители между &apos;=&apos;, названием и значением параметра {1} недопустимы..
        /// </summary>
        internal static string IcorrectMacroCallKeyParameter {
            get {
                return ResourceManager.GetString("IcorrectMacroCallKeyParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр {0} макроопределения определен некорректно.
        /// </summary>
        internal static string IcorrectMacroDefinitionParameter {
            get {
                return ResourceManager.GetString("IcorrectMacroDefinitionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение по умолчанию для параметра {0} макроопределения определено некорректно.
        /// </summary>
        internal static string IcorrectMacroDefinitionParameterDefault {
            get {
                return ResourceManager.GetString("IcorrectMacroDefinitionParameterDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры макроопределения {0} определены некорректно.
        /// </summary>
        internal static string IcorrectMacroDefinitionParameters {
            get {
                return ResourceManager.GetString("IcorrectMacroDefinitionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аргументы командной строки некорректны.
        /// </summary>
        internal static string IncorrectCmdArguments {
            get {
                return ResourceManager.GetString("IncorrectCmdArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорретно задан аргумент командной строки. Скорее всего Вы имели в виду {0}.
        /// </summary>
        internal static string IncorrectCmdKey {
            get {
                return ResourceManager.GetString("IncorrectCmdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное количество аргументов командной строки.
        /// </summary>
        internal static string IncorrectCmdKeysCount {
            get {
                return ResourceManager.GetString("IncorrectCmdKeysCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аргументы командной строки заданы некорректно.
        /// </summary>
        internal static string IncorrectCmdKeysUsage {
            get {
                return ResourceManager.GetString("IncorrectCmdKeysUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено некорректно заданное условие. {0} не является переменной и числом.
        /// </summary>
        internal static string IncorrectConditionPart {
            get {
                return ResourceManager.GetString("IncorrectConditionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное количество операндов в директиве {0}.
        /// </summary>
        internal static string IncorrectDirectiveOperands {
            get {
                return ResourceManager.GetString("IncorrectDirectiveOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное использование директивы {0}.
        /// </summary>
        internal static string IncorrectDirectiveUsage {
            get {
                return ResourceManager.GetString("IncorrectDirectiveUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы ввели неверный ключ.
        /// </summary>
        internal static string IncorrectKeyEntered {
            get {
                return ResourceManager.GetString("IncorrectKeyEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректно указаны параметры при вызове макроса {0}.
        /// </summary>
        internal static string IncorrectMacroCallParameters {
            get {
                return ResourceManager.GetString("IncorrectMacroCallParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное количество параметров при вызове макроса {0}.
        /// </summary>
        internal static string IncorrectMacroCallParametersCount {
            get {
                return ResourceManager.GetString("IncorrectMacroCallParametersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя макроса {0} некорректно.
        /// </summary>
        internal static string IncorrectMacroName {
            get {
                return ResourceManager.GetString("IncorrectMacroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя параметра макроса {0} некорректно.
        /// </summary>
        internal static string IncorrectMacroParameterName {
            get {
                return ResourceManager.GetString("IncorrectMacroParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр {0} не является ключевым.
        /// </summary>
        internal static string IncorrectMacroParameterType {
            get {
                return ResourceManager.GetString("IncorrectMacroParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр макроса {0} некорректен.
        /// </summary>
        internal static string IncorrectMacroParameterValue {
            get {
                return ResourceManager.GetString("IncorrectMacroParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название глобальной переменной {0} некорректно.
        /// </summary>
        internal static string IncorrectVariableName {
            get {
                return ResourceManager.GetString("IncorrectVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение глобальной переменной {0} некорректно.
        /// </summary>
        internal static string IncorrectVariableValue {
            get {
                return ResourceManager.GetString("IncorrectVariableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найден бесконечный цикл.
        /// </summary>
        internal static string InfiniteLoop {
            get {
                return ResourceManager.GetString("InfiniteLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директива {0} не должна содержать метки.
        /// </summary>
        internal static string LabelInDirective {
            get {
                return ResourceManager.GetString("LabelInDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метки внутри макроса {0} недопустимы.
        /// </summary>
        internal static string LabelInMacro {
            get {
                return ResourceManager.GetString("LabelInMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызов макроса не должен сожержать меток.
        /// </summary>
        internal static string LabelInMacroCall {
            get {
                return ResourceManager.GetString("LabelInMacroCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макроопределение не должно сожержать меток.
        /// </summary>
        internal static string LabelInMacroDefinition {
            get {
                return ResourceManager.GetString("LabelInMacroDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка использования директивы AGO или AIF. Метка в пределах макроса {0} не найдена.
        /// </summary>
        internal static string LabelInMacroNotFound {
            get {
                return ResourceManager.GetString("LabelInMacroNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директива MEND не должна содержать меток.
        /// </summary>
        internal static string LabelInMend {
            get {
                return ResourceManager.GetString("LabelInMend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директива SET не должна содержать меток.
        /// </summary>
        internal static string LabelInSetVariable {
            get {
                return ResourceManager.GetString("LabelInSetVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директива GLOBAL не должна содержать меток.
        /// </summary>
        internal static string LabelInVariableDefinition {
            get {
                return ResourceManager.GetString("LabelInVariableDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макровызовы внутри макроса запрещены.
        /// </summary>
        internal static string MacroCallInMacro {
            get {
                return ResourceManager.GetString("MacroCallInMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перекрестные ссылки и рекурсия запрещены.
        /// </summary>
        internal static string MacroCallRecursion {
            get {
                return ResourceManager.GetString("MacroCallRecursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макроопределения внутри макроса запрещены.
        /// </summary>
        internal static string MacroDefinitionInMacro {
            get {
                return ResourceManager.GetString("MacroDefinitionInMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макроопределения внутри макроса запрещены.
        /// </summary>
        internal static string MacroDefinitionInsideMacro {
            get {
                return ResourceManager.GetString("MacroDefinitionInsideMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макрос {0} уже описан.
        /// </summary>
        internal static string MacroDublicate {
            get {
                return ResourceManager.GetString("MacroDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество директив MACRO и MEND не совпадает.
        /// </summary>
        internal static string MacroIsIncomplete {
            get {
                return ResourceManager.GetString("MacroIsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макрос {0} не входит в область видимости {1}.
        /// </summary>
        internal static string MacroIsNotInLocalTmo {
            get {
                return ResourceManager.GetString("MacroIsNotInLocalTmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объявление макросов и переменных в цикле запрещено.
        /// </summary>
        internal static string MacroOrVariableInLoop {
            get {
                return ResourceManager.GetString("MacroOrVariableInLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя параметра {0} уже описано.
        /// </summary>
        internal static string MacroParameterDublicate {
            get {
                return ResourceManager.GetString("MacroParameterDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр {0} - неинициализованная переменная.
        /// </summary>
        internal static string MacroParameterIsEmptyVariable {
            get {
                return ResourceManager.GetString("MacroParameterIsEmptyVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У макроса {0} не должно быть параметров.
        /// </summary>
        internal static string MacroShouldNotHaveParams {
            get {
                return ResourceManager.GetString("MacroShouldNotHaveParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя {0} уже используется как название макроса.
        /// </summary>
        internal static string NameAleradyInUseAsMacro {
            get {
                return ResourceManager.GetString("NameAleradyInUseAsMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя {0} уже используется как переменная макроса.
        /// </summary>
        internal static string NameAleradyInUseAsMacroParameter {
            get {
                return ResourceManager.GetString("NameAleradyInUseAsMacroParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя {0}  уже используется как название глобальной переменной.
        /// </summary>
        internal static string NameAleradyInUseAsVariable {
            get {
                return ResourceManager.GetString("NameAleradyInUseAsVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующий шаг выполнен.
        /// </summary>
        internal static string NextStepExecuted {
            get {
                return ResourceManager.GetString("NextStepExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр {0} не существует в макроопределении.
        /// </summary>
        internal static string ParameterDoesNotExists {
            get {
                return ResourceManager.GetString("ParameterDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директива MEND не должна содержать параметров.
        /// </summary>
        internal static string ParametersInMend {
            get {
                return ResourceManager.GetString("ParametersInMend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макропроцессор завершил свою работу.
        /// </summary>
        internal static string ProcessingEnded {
            get {
                return ResourceManager.GetString("ProcessingEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Второй проход завершен.
        /// </summary>
        internal static string SecondRunFinished {
            get {
                return ResourceManager.GetString("SecondRunFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макропроцессор уже работает в пошаговом режиме. .
        /// </summary>
        internal static string StepModeStarted {
            get {
                return ResourceManager.GetString("StepModeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись успешно завершена.
        /// </summary>
        internal static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слишком много двоеточий в строке &quot;{0}&quot;.
        /// </summary>
        internal static string TooMuchColons {
            get {
                return ResourceManager.GetString("TooMuchColons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить данные из файла.
        /// </summary>
        internal static string UnableToLoadDataFromFile {
            get {
                return ResourceManager.GetString("UnableToLoadDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись завершена с ошибкой.
        /// </summary>
        internal static string UnableToSaveIntoFile {
            get {
                return ResourceManager.GetString("UnableToSaveIntoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный знак сравнения.
        /// </summary>
        internal static string UndefinedComparisonSign {
            get {
                return ResourceManager.GetString("UndefinedComparisonSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неопознанная операция {0}.
        /// </summary>
        internal static string UndefinedOperation {
            get {
                return ResourceManager.GetString("UndefinedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неинициализированная глобальная переменная {0} является частью условия.
        /// </summary>
        internal static string UndefinedVariableIsComparisonPart {
            get {
                return ResourceManager.GetString("UndefinedVariableIsComparisonPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в строке &quot;{0}&quot;.
        /// </summary>
        internal static string UnexpectedErrorOccured {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Глобальная переменная {0} уже описана.
        /// </summary>
        internal static string VariableDublicate {
            get {
                return ResourceManager.GetString("VariableDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя объявлять переменные в цикле.
        /// </summary>
        internal static string VariablesInLoop {
            get {
                return ResourceManager.GetString("VariablesInLoop", resourceCulture);
            }
        }
    }
}
